# Generated by Django 5.2.5 on 2025-08-31 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='about_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='about_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='mission_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='mission_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='vision_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='vision_en',
            field=models.TextField(null=True),
        ),
    ]
