# Generated by Django 5.2.5 on 2025-08-31 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_companyinfo_about_ar_companyinfo_about_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.AddField(
            model_name='project',
            name='completion_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sector',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='issue_date',
            field=models.DateField(null=True),
        ),
    ]
