# Generated by Django 5.2.5 on 2025-08-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_project_category_project_completion_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSEPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='hse_policies/')),
                ('lang', models.CharField(choices=[('EN', 'English'), ('AR', 'Arabic')], default='EN', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='QualityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='quality_policies/')),
                ('lang', models.CharField(choices=[('EN', 'English'), ('AR', 'Arabic')], default='EN', max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='certification',
            name='issue_date',
        ),
        migrations.AddField(
            model_name='certification',
            name='lang',
            field=models.CharField(choices=[('EN', 'English'), ('AR', 'Arabic')], default='EN', max_length=2),
        ),
    ]
