# Generated by Django 5.2.6 on 2025-10-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_contactmessage_jobapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='file',
        ),
        migrations.AddField(
            model_name='certification',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
